version: '3.9'

networks:
  default:
  reverse_proxy:
    external: true

volumes:
  mysql_data:
  redis_data:

services:

  web:
    build:
      context: ./nginx
      args:
        - USER_ID=${USER_ID:-1000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl /dev/null localhost || exit 1"]
    # ports: 
    #   - "8080:80"
    links:
      - php
    environment:
      # Used by nginx-proxy
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=80
    volumes:
      - ./${SOURCE_DIR}:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - redis
      - mysql
    networks:
      - default
      - reverse_proxy

  php:
    build:
      context: ./php
      args:
        - USER_ID=${USER_ID:-1000}
    restart: unless-stopped
    volumes:
      - ./${SOURCE_DIR}:/var/www/html
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/health-check.sh"]

  mysql:
    image: mariadb:10.5
    restart: unless-stopped
    tty: true
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
          test: ["CMD", "redis-cli", "ping"]

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
    profiles:
      - tools

  npm:
    image: node:lts-alpine3.14
    volumes:
      - ./${SOURCE_DIR}:/var/www/html
    ports:
      - "3000:3000"
      - "3001:3001"
    working_dir: /var/www/html
    entrypoint: ['npm']
    user: 1000:1000
    profiles:
      - tools
