services:

  mailhog:
    build: ./config/mailhog
    environment:
        TZ: ${TIMEZONE:-UTC}
    ports:
        - 8025:8025
    profiles:
        - utils

  npm:
    image: node:lts-alpine3.14
    volumes:
        - ./${SOURCE_DIR}:/var/www/html
    user: $USER_ID:$USER_ID
    environment:
        TZ: ${TIMEZONE:-UTC}
    working_dir: /var/www/html
    entrypoint: [npm]
    ports:
        - 3000:3000
        - 3001:3001
    profiles:
        - utils
