networks:
    reverse_proxy:
        external: true

volumes:
    mysql_data:
    redis_data:

services:
    nginx:
        build:
            context: ./config/nginx
        volumes:
            - ./${SOURCE_DIR}:/var/www/html
            - ./config/nginx/files/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx/files/default.conf:/etc/nginx/conf.d/default.conf
        environment:
            TZ: ${TIMEZONE:-UTC}
            VIRTUAL_HOST:
        ports:
            - 8080:80
        restart: unless-stopped
        healthcheck:
            test: [CMD-SHELL, curl /dev/null localhost || exit 1]
        depends_on:
            - php
            - mysql
            - redis
        networks:
            - default
            - reverse_proxy
    php:
        build:
            context: ./config/php
            args:
                USER_ID: ${USER_ID:-0}
        user: $USER_ID:$USER_ID
        environment:
            TZ: ${TIMEZONE:-UTC}
        volumes:
            - ./${SOURCE_DIR}:/var/www/html
            - ./config/php/files/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        working_dir: /var/www/html
        restart: unless-stopped
        healthcheck:
            test: [CMD-SHELL, health-check.sh]
    mysql:
        build: ./config/mysql
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            TZ: ${TIMEZONE:-UTC}
            MYSQL_DATABASE:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_ROOT_PASSWORD:
        restart: unless-stopped
        healthcheck:
            test: [CMD, mysqladmin ,ping, -h, localhost]
    redis:
        image: redis:6.2-alpine
        volumes:
            - redis_data:/data
        environment:
            TZ: ${TIMEZONE:-UTC}
        restart: unless-stopped
        healthcheck:
            test: [CMD, redis-cli, ping]
